# ImmortalWrt 第三方插件配置
# 每行一个包，格式：CONFIG_PACKAGE_包名=y
# 此文件在 diy-part2.d/immortalwrt.sh 中自动追加到 .config
CONFIG_PACKAGE_luci-app-run=y
CONFIG_PACKAGE_mihomo-meta=y
CONFIG_PACKAGE_nikki=y
CONFIG_PACKAGE_luci-i18n-nikki-zh-cn=y
CONFIG_PACKAGE_luci-app-nikki=y
CONFIG_PACKAGE_luci-app-poweroffdevice=y
